// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/list-conversions.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.106.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-conversions.ts
var list_conversions_default = defineTool({
  name: "list_conversions",
  title: "Listar convers\xF5es",
  description: "Lista os eventos de convers\xE3o recentes (cliques, leads e compras) registrados pelo site LipoVitta.",
  inputSchema: {
    days: z.number().int().min(1).max(365).default(7).describe("Per\xEDodo em dias a consultar."),
    event_name: z.string().optional().describe("Filtrar por evento, ex.: Purchase, InitiateCheckout, Lead."),
    limit: z.number().int().min(1).max(200).default(50).describe("M\xE1ximo de linhas.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days, event_name, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const since = new Date(Date.now() - days * 864e5).toISOString();
    let query = supabase.from("conversion_events").select(
      "id,event_name,source,cta_location,product_name,value,order_id,gift,utm_source,utm_campaign,meta_status,created_at"
    ).gte("created_at", since).order("created_at", { ascending: false }).limit(limit);
    if (event_name) query = query.eq("event_name", event_name);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { events: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/conversion-summary.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^3.25.76";
var conversion_summary_default = defineTool2({
  name: "conversion_summary",
  title: "Resumo de convers\xF5es",
  description: "Resume o desempenho do per\xEDodo: cliques, leads, compras, receita total e origens (UTM) mais fortes. Os totais s\xE3o calculados no banco (sem truncagem) e pedidos de teste ficam fora por padr\xE3o.",
  inputSchema: {
    days: z2.number().int().min(1).max(365).default(30).describe("Per\xEDodo em dias."),
    include_tests: z2.boolean().default(false).describe("Incluir pedidos de teste (TEST...) no c\xE1lculo.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days, include_tests }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("mcp_conversion_summary", {
      _days: days,
      _include_tests: include_tests ?? false
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const summary = data ?? {};
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-applications.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_applications_default = defineTool3({
  name: "list_applications",
  title: "Listar candidaturas",
  description: "Lista as candidaturas recebidas de afiliadas ou de parceiros comerciais do site LipoVitta.",
  inputSchema: {
    type: z3.enum(["afiliada", "parceiro"]).default("afiliada").describe("Tipo de candidatura a listar."),
    limit: z3.number().int().min(1).max(100).default(25).describe("M\xE1ximo de linhas.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ type, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const table = type === "parceiro" ? "commercial_partner_applications" : "affiliate_applications";
    const { data, error } = await supabase.from(table).select("*").order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { type, items: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ecgquvfoipmoqlhfkfol";
var mcp_default = defineMcp({
  name: "lipovitta-transformation",
  title: "LipoVitta Transformation",
  version: "0.1.0",
  instructions: "Ferramentas da LipoVitta. Use `conversion_summary` para o panorama de vendas do per\xEDodo, `list_conversions` para eventos detalhados (cliques, leads, compras) e `list_applications` para candidaturas de afiliadas e parceiros. Os dados respeitam as permiss\xF5es da conta conectada (apenas administradores enxergam os registros).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [conversion_summary_default, list_conversions_default, list_applications_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
