// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/list-conversions.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.106.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-conversions.ts
var list_conversions_default = defineTool({
  name: "list_conversions",
  title: "Listar convers\xF5es",
  description: "Lista os eventos de convers\xE3o recentes (cliques, leads e compras) registrados pelo site LipoVitta.",
  inputSchema: {
    days: z.number().int().min(1).max(365).default(7).describe("Per\xEDodo em dias a consultar."),
    event_name: z.string().optional().describe("Filtrar por evento, ex.: Purchase, InitiateCheckout, Lead."),
    limit: z.number().int().min(1).max(200).default(50).describe("M\xE1ximo de linhas.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days, event_name, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const since = new Date(Date.now() - days * 864e5).toISOString();
    let query = supabase.from("conversion_events").select(
      "id,event_name,source,cta_location,product_name,value,order_id,gift,utm_source,utm_campaign,meta_status,created_at"
    ).gte("created_at", since).order("created_at", { ascending: false }).limit(limit);
    if (event_name) query = query.eq("event_name", event_name);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { events: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/conversion-summary.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^3.25.76";
var conversion_summary_default = defineTool2({
  name: "conversion_summary",
  title: "Resumo de convers\xF5es",
  description: "Resume o desempenho do per\xEDodo: cliques, leads, compras, receita total e origens (UTM) mais fortes. Os totais s\xE3o calculados no banco (sem truncagem) e pedidos de teste ficam fora por padr\xE3o.",
  inputSchema: {
    days: z2.number().int().min(1).max(365).default(30).describe("Per\xEDodo em dias."),
    include_tests: z2.boolean().default(false).describe("Incluir pedidos de teste (TEST...) no c\xE1lculo.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days, include_tests }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("mcp_conversion_summary", {
      _days: days,
      _include_tests: include_tests ?? false
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const summary = data ?? {};
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-applications.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_applications_default = defineTool3({
  name: "list_applications",
  title: "Listar candidaturas",
  description: "Lista as candidaturas recebidas de afiliadas ou de parceiros comerciais do site LipoVitta.",
  inputSchema: {
    type: z3.enum(["afiliada", "parceiro"]).default("afiliada").describe("Tipo de candidatura a listar."),
    limit: z3.number().int().min(1).max(100).default(25).describe("M\xE1ximo de linhas.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ type, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const table = type === "parceiro" ? "commercial_partner_applications" : "affiliate_applications";
    const { data, error } = await supabase.from(table).select("*").order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { type, items: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/sales-metrics.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z4 } from "npm:zod@^3.25.76";
var sales_metrics_default = defineTool4({
  name: "sales_metrics",
  title: "M\xE9tricas de vendas",
  description: "Compradores \xFAnicos, n\xFAmero de pedidos, faturamento, ticket m\xE9dio, taxa de convers\xE3o a partir dos checkouts iniciados e produtos mais vendidos. Exclui pedidos de teste por padr\xE3o.",
  inputSchema: {
    days: z4.number().int().min(1).max(365).default(30).describe("Per\xEDodo em dias."),
    include_tests: z4.boolean().default(false).describe("Incluir pedidos de teste (TEST...) no c\xE1lculo.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days, include_tests }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("mcp_sales_metrics", {
      _days: days,
      _include_tests: include_tests ?? false
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const metrics = data ?? {};
    return {
      content: [{ type: "text", text: JSON.stringify(metrics) }],
      structuredContent: metrics
    };
  }
});

// src/lib/mcp/tools/tracking-health.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z5 } from "npm:zod@^3.25.76";
var tracking_health_default = defineTool5({
  name: "tracking_health",
  title: "Sa\xFAde do rastreamento",
  description: "Compara checkouts iniciados, carrinhos abandonados, pedidos pagos, Purchase interno e envio para a Meta. Aponta inconsist\xEAncias, erros error_404 e diverg\xEAncias de pre\xE7o.",
  inputSchema: {
    days: z5.number().int().min(1).max(365).default(7).describe("Per\xEDodo em dias."),
    include_tests: z5.boolean().default(false).describe("Incluir pedidos de teste (TEST...) na an\xE1lise.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days, include_tests }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("mcp_tracking_health", {
      _days: days,
      _include_tests: include_tests ?? false
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const health = data ?? {};
    const gaps = [];
    const num = (k) => Number(health[k] ?? 0);
    if (num("meta_error_404") > 0)
      gaps.push(`${num("meta_error_404")} compras com meta_status=error_404 (endpoint CAPI inv\xE1lido).`);
    if (num("meta_missing_status") > 0)
      gaps.push(`${num("meta_missing_status")} compras sem status de envio para a Meta.`);
    if (num("internal_purchases") > 0 && num("meta_sent") < num("internal_purchases"))
      gaps.push(
        `Apenas ${num("meta_sent")} de ${num("internal_purchases")} compras chegaram \xE0 Meta.`
      );
    if (num("price_mismatches") > 0)
      gaps.push(`${num("price_mismatches")} pedidos com diverg\xEAncia entre valor esperado e pago.`);
    if (num("initiate_checkouts") > 0 && num("internal_purchases") === 0)
      gaps.push("Houve checkouts iniciados, mas nenhuma compra registrada no per\xEDodo.");
    const result = { ...health, gaps };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-abandoned-checkouts.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z6 } from "npm:zod@^3.25.76";
var list_abandoned_checkouts_default = defineTool6({
  name: "list_abandoned_checkouts",
  title: "Listar carrinhos abandonados",
  description: "Lista os carrinhos abandonados capturados pelo webhook da Yampi: nome, telefone, e-mail, produtos, valor, UTMs, links de recupera\xE7\xE3o/recompra e data. Cont\xE9m dados pessoais \u2014 apenas administradores conseguem ler.",
  inputSchema: {
    days: z6.number().int().min(1).max(365).default(7).describe("Per\xEDodo em dias."),
    limit: z6.number().int().min(1).max(200).default(50).describe("M\xE1ximo de linhas."),
    only_unrecovered: z6.boolean().default(true).describe("Mostrar apenas carrinhos ainda n\xE3o recuperados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days, limit, only_unrecovered }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const since = new Date(Date.now() - days * 864e5).toISOString();
    let query = supabase.from("abandoned_checkouts").select(
      "cart_token,customer_name,customer_email,customer_phone,items,total,currency,recovery_url,reorder_url,utm_source,utm_medium,utm_campaign,utm_content,utm_term,abandoned_at,recovered_at,recovered_order_id"
    ).gte("abandoned_at", since).order("abandoned_at", { ascending: false }).limit(limit);
    if (only_unrecovered) query = query.is("recovered_at", null);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const items = data ?? [];
    const payload = { items, count: items.length, days, only_unrecovered };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-yampi-orders.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z7 } from "npm:zod@^3.25.76";
var list_yampi_orders_default = defineTool7({
  name: "list_yampi_orders",
  title: "Listar pedidos Yampi",
  description: "Lista os pedidos registrados pelo webhook da Yampi (criados, aguardando pagamento, pagos, cancelados) com status, itens, valores, UTMs, brinde e diverg\xEAncias de pre\xE7o. Pedidos de teste (TEST...) ficam fora por padr\xE3o.",
  inputSchema: {
    days: z7.number().int().min(1).max(365).default(30).describe("Per\xEDodo em dias."),
    limit: z7.number().int().min(1).max(200).default(50).describe("M\xE1ximo de linhas."),
    status: z7.string().optional().describe("Filtrar por status da Yampi, ex.: paid, waiting_payment, cancelled."),
    include_tests: z7.boolean().default(false).describe("Incluir pedidos de teste."),
    only_mismatches: z7.boolean().default(false).describe("Mostrar apenas pedidos com diverg\xEAncia de pre\xE7o.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days, limit, status, include_tests, only_mismatches }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const since = new Date(Date.now() - days * 864e5).toISOString();
    let query = supabase.from("yampi_orders").select(
      "order_id,order_number,status,event,value_total,value_products,value_discount,payment_alias,items,utm_source,utm_medium,utm_campaign,utm_content,utm_term,event_id,gift,expected_value,price_diff,price_mismatch,is_test,created_at_yampi,updated_at_yampi,first_seen_at,last_seen_at"
    ).gte("last_seen_at", since).order("last_seen_at", { ascending: false }).limit(limit);
    if (!include_tests) query = query.eq("is_test", false);
    if (status?.trim()) query = query.eq("status", status.trim().toLowerCase());
    if (only_mismatches) query = query.eq("price_mismatch", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const orders = (data ?? []).map((row) => ({
      order_id: row.order_id,
      order_number: row.order_number,
      status: row.status,
      last_event: row.event,
      value_total: row.value_total,
      value_products: row.value_products,
      value_discount: row.value_discount,
      payment: row.payment_alias,
      items: row.items,
      utm: {
        source: row.utm_source,
        medium: row.utm_medium,
        campaign: row.utm_campaign,
        content: row.utm_content,
        term: row.utm_term
      },
      event_id: row.event_id,
      gift: row.gift,
      expected_value: row.expected_value,
      price_diff: row.price_diff,
      price_mismatch: row.price_mismatch,
      is_test: row.is_test,
      created_at_yampi: row.created_at_yampi,
      updated_at_yampi: row.updated_at_yampi,
      first_seen_at: row.first_seen_at,
      last_seen_at: row.last_seen_at
    }));
    const payload = { orders, count: orders.length, days, status: status ?? null, include_tests };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ecgquvfoipmoqlhfkfol";
var mcp_default = defineMcp({
  name: "lipovitta-transformation",
  title: "LipoVitta Transformation",
  version: "0.3.0",
  instructions: "Ferramentas operacionais da LipoVitta (loja Yampi + rastreamento Meta). Leitura: `sales_metrics` para faturamento, ticket m\xE9dio e convers\xE3o; `conversion_summary` para o panorama de eventos; `list_yampi_orders` para pedidos reais com status, itens e diverg\xEAncias de pre\xE7o; `list_abandoned_checkouts` para carrinhos abandonados com contato e link de recupera\xE7\xE3o; `list_conversions` para o log bruto de eventos; `list_applications` para candidaturas de afiliadas e parceiros; `tracking_health` para conferir se checkouts, pedidos pagos, Purchase interno e envio \xE0 Meta batem. Pedidos de teste (TEST...) s\xE3o exclu\xEDdos por padr\xE3o \u2014 use include_tests para v\xEA-los. Todos os dados respeitam as permiss\xF5es da conta conectada: apenas administradores enxergam registros e dados pessoais. Nenhuma ferramenta escreve dados nesta vers\xE3o.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    sales_metrics_default,
    conversion_summary_default,
    list_yampi_orders_default,
    list_abandoned_checkouts_default,
    list_conversions_default,
    list_applications_default,
    tracking_health_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
